# Generated by Django 5.1.2 on 2024-11-01 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('year', models.CharField(default='', max_length=100, verbose_name='Год выпуска')),
                ('film', models.CharField(default='', max_length=255, verbose_name='Видео')),
                ('director', models.CharField(default='', max_length=255, verbose_name='Режиссер')),
                ('description', models.TextField(default='', verbose_name='Описание фильма ')),
                ('promoPhoto', models.ImageField(default='', upload_to='images/promo/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koruflex_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок - продолжить просмтор')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('video', models.CharField(default='', max_length=255, verbose_name='Видео')),
                ('yearRelese', models.CharField(max_length=100, verbose_name='Год выауска')),
                ('promoPhoto', models.ImageField(default='', upload_to='images/promo/', verbose_name='Фото')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='koruflex_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Просмотренное',
                'verbose_name_plural': 'Просмотренные',
            },
        ),
    ]
