# Generated by Django 5.1.2 on 2024-11-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koruflex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='promoPhoto',
            field=models.ImageField(default='', upload_to='images/histories/', verbose_name='Фото'),
        ),
    ]
